os: linux
language: node_js # Node.js based project
node_js:
  - 14 # Level of Node.js to use
cache:
  yarn: true
  directories:
  - marketing/node_modules # Cache the node_modules folder for quicker build times
before_script:
  - cd marketing
  - yarn install
script:
  - yarn build # Runs next build
  - yarn run export # Runs next export and generates the out directory
  - touch out/.nojekyll # Creates a file telling Github not to build the project using Jekyll
deploy:
  provider: pages # Informs Travis this is a deployment to GitHub Pages
  cleanup: true # Prevents Travis from resetting the working directory made during the build
  github_token: $github_token # GitHub access token to use when pushing to the gh-pages branch
  local_dir: marketing/out # Directory to push to the gh-pages branch
  on:
    # Only deploy when the build is on master or main branch - two common default branch names
    # If you're using a different branch name, add it here
    all_branches: true
    condition: $TRAVIS_BRANCH =~ ^(master|main)$