name: API e2e tests

on:
  push:
    paths:
      - '.github/**'
      - 'api/**'
  workflow_dispatch:

env:
  NODE_ENV: test
  DB_HOST: localhost
  DB_USERNAME: landgriffon
  DB_PASSWORD: landgriffon
  DB_DATABASE: landgriffon
  CC_TEST_REPORTER_ID: 29691479b26fbb03a9d926e1d6b0bba99c7eae3bb235e26a8b269219fe3c62fc

defaults:
  run:
    working-directory: api

jobs:
  api-tests:
    name: API E2E tests
    runs-on: ubuntu-20.04
    timeout-minutes: 15

    services:
      postgres:
        image: postgis/postgis:13-3.1
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: landgriffon
          POSTGRES_PASSWORD: landgriffon

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js 14.16
        uses: actions/setup-node@v2
        with:
          node-version: '14.16'

      - name: Install dependencies
        run: yarn install

      - name: Run tests
        run: yarn test

      - name: Run coverage
        uses: paambaati/codeclimate-action@v2.7.5
        with:
          working-directory: api
          coverageCommand: yarn test:cov

